branches:
  only:
    - master
language: java
services:
  - docker
jdk:
  - openjdk7
sudo: enabled
before_install:
  - /bin/bash rubix_travis_before_install.sh
install: true
script: /bin/bash rubix_travis_script.sh
env:
  - ci_env=`bash <(curl -s https://codecov.io/env)`
